### ISSUE TITLE
TypeError: Object #<Object> has no method 'showSeasons'

### ISSUE THREAD

**Issue by TehPirat3** [sharkone/scrapyard.js#1]
[HTTP][MEM][00.0s] https://api-v2launch.trakt.tv/shows/rick-and-morty?extended=full%2Cimages
TypeError: Object #<Object> has no method 'showSeasons'
    at getSeasons (/var/www/html/scrapyard.js/shows.js:74:9)
    at async.parallel.i (/var/www/html/scrapyard.js/shows.js:180:9)
    at /var/www/html/scrapyard.js/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/var/www/html/scrapyard.js/node_modules/async/lib/async.js:233:13)
    at _parallel (/var/www/html/scrapyard.js/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/var/www/html/scrapyard.js/node_modules/async/lib/async.js:731:9)
    at Object.exports.getInfo (/var/www/html/scrapyard.js/shows.js:167:9)
    at /var/www/html/scrapyard.js/index.js:176:9
    at Layer.handle [as handle_request](/var/www/html/scrapyard.js/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/scrapyard.js/node_modules/express/lib/router/route.js:131:13)

**Comment by sharkone** [comment]
Hahah of course as it's not implemented yet!
You're lurking around ? :D

**Comment by TehPirat3** [comment]
I was having some connection issues with your default server, latency wise, so hosting it locally myself alongside plex :P

**Comment by sharkone** [comment]
Well the "public" server currently runs the python version [here](https://github.com/sharkone/scrapyard), and this is a new rewrite using Node.js. It's not complete yet. But well, feel free to poke around :)

**Comment by TehPirat3** [comment]
I was actually having issues with the python version. It wouldn't detect 'scrapyard' as a packaged module. Being unfamiliar with python and very familiar with java, I got this version running right away.

**Comment by sharkone** [comment]
Should be all good now.
