### ISSUE TITLE
Object #<Object> has no method 'gzipSync'

### ISSUE THREAD

**Issue by TehPirat3** [sharkone/scrapyard.js#3]
[HTTP][NET][00.4s] https://api-v2launch.trakt.tv/shows/trending?page=1&limit=31

TypeError: Object #<Object> has no method 'gzipSync'
    at /var/www/html/scrapyard.js/network.js:77:37
    at Request._callback (/var/www/html/scrapyard.js/network.js:56:7)
    at Request.self.callback (/var/www/html/scrapyard.js/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/html/scrapyard.js/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:117:20)
    at Gunzip.<anonymous> (/var/www/html/scrapyard.js/node_modules/request/request.js:963:12)
    at Gunzip.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by TehPirat3** [comment]
issue resolved after force node update. though a new issue was risen. Unable to view popular/trending tv shows, search function works.

**Comment by sharkone** [comment]
Closing then.
